# Generated by Django 3.1.7 on 2021-04-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemovel',
            fields=[
                ('nome', models.CharField(default='', max_length=8000, unique='false')),
                ('link', models.CharField(default='', max_length=8000, primary_key=True, serialize=False, unique='true')),
                ('modelo', models.CharField(default='', max_length=30, unique='false')),
                ('negociavel', models.BooleanField(default=False)),
                ('preco', models.IntegerField()),
                ('descricao', models.CharField(default='', max_length=8000, unique='false')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30, unique='true')),
                ('password', models.CharField(default='', max_length=50, unique='false')),
            ],
        ),
    ]
